[package]
name = "minecraft_data_types"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.8.2", features = ["v4"] }
hematite-nbt = "0.5.2"
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1", features = [ "io-util" ]}
